CREATE TABLE `sellerApplications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`applicantName` varchar(255) NOT NULL,
	`applicantEmail` varchar(320) NOT NULL,
	`applicantPhone` varchar(20) NOT NULL,
	`businessName` varchar(255) NOT NULL,
	`businessType` varchar(100) NOT NULL,
	`businessAddress` text NOT NULL,
	`businessDescription` text,
	`idDocument` text,
	`businessLicense` text,
	`taxCertificate` text,
	`proofOfAddress` text,
	`bankName` varchar(100),
	`bankAccountNumber` varchar(50),
	`mobileMoneyProvider` enum('mtn_money','orange_money'),
	`mobileMoneyNumber` varchar(20),
	`status` enum('pending','under_review','approved','rejected','requires_info') NOT NULL DEFAULT 'pending',
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`reviewNotes` text,
	`rejectionReason` text,
	`sellerId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `sellerApplications_id` PRIMARY KEY(`id`)
);
